liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

google.vision.api.key: AIzaSyDaE7_gg2YLS5-NuSCEaSXF1CdK63EwARE
