liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

# slack integrations
rtmUrl: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
slackBotToken: xoxb-167203214182-iPgstcmcKaT1pHtDwZR7F8AH
slashCommandToken: X73Fv3Tokenx242CdpEq
slackIncomingWebhookUrl: https://hooks.slack.com/services/T025DUwebhookurloOYvPiHL7y6
